spring.application.name=ajay-product-service

#DB details
#spring.data.mongodb.uri=mongodb+srv://yadavajay81:3wjN4OUH18fasf0q@cluster0.buopw1w.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 


#mongodb+srv://yadavajay81:ClccLnXm1DttlUMO@cluster0.q9ojwga.mongodb.net/


spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://localhost:3306/ajay-product-service
spring.datasource.username=ecommerceapp
spring.datasource.password=ecommerceapp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver